[project]
name = "mangasorigines"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["bs4>=0.0.2", "cloudscraper>=1.2.71", "tqdm>=4.67.1"]

[dependency-groups]
dev = ["ruff>=0.12.7"]
